[package]
name = "galton-board-pseudo-random-simulation"
version = "0.3.0"
edition = "2023"

[dependencies]
image = "0.24"
rand = "0.8"

[[bin]]
name = "galton-board"
path = "fujitsu/laptop/onday_november_10th_2025/utx-98012-galton-board-rust/src/galton_board.rs"